/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzdongcheng_alxdrivers_jni_JNIModbus */

#ifndef _Included_com_hzdongcheng_alxdrivers_jni_JNIModbus
#define _Included_com_hzdongcheng_alxdrivers_jni_JNIModbus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzdongcheng_alxdrivers_jni_JNIModbus
 * Method:    CreateMasterRTU
 * Signature: (Ljava/lang/String;ICII)J
 */
JNIEXPORT jlong JNICALL Java_com_hzdongcheng_alxdrivers_jni_JNIModbus_CreateMasterRTU
  (JNIEnv *, jobject, jstring, jint, jchar, jint, jint);

/*
 * Class:     com_hzdongcheng_alxdrivers_jni_JNIModbus
 * Method:    Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hzdongcheng_alxdrivers_jni_JNIModbus_Close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_hzdongcheng_alxdrivers_jni_JNIModbus
 * Method:    ReadRegisters
 * Signature: (JIII[C)I
 */
JNIEXPORT jint JNICALL Java_com_hzdongcheng_alxdrivers_jni_JNIModbus_ReadRegisters
  (JNIEnv *, jobject, jlong, jint, jint, jint, jcharArray);

/*
 * Class:     com_hzdongcheng_alxdrivers_jni_JNIModbus
 * Method:    WriteRegister
 * Signature: (JIII[C)I
 */
JNIEXPORT jint JNICALL Java_com_hzdongcheng_alxdrivers_jni_JNIModbus_WriteRegister
  (JNIEnv *, jobject, jlong, jint, jint, jint, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
